from instapy import InstaPy
import time

session = InstaPy(username="khandaghe_bala",password="britney55655?")
session.login()
while(True):
	session.like_by_tags(["iranmusic"], amount=1,randomize=True)
	session.set_do_comment(True,percentage=100)
	session.set_comments(["age mishe mano follow konidd","lotfan mano follow konidd","mamnoon misham mano follow konidd","mishe mano follow konidd?","lotfan mano follow konidd dooste azizz","salam age momkene mano follow konidd","kheili khube , lotfan page e man ro ham bebinidd", "age emkanesh hast mano follow konidd lotfannn", "mishe axaye mano like konii?", "lotfan mano follow konidd", "mishe khahesh konam mano follow konidd?","lotf konid man ro ham follow konidd","lotfan age emkansh hast mano follow konidd","mishe khahesh konam az man hemayat konidd?","age lotf konid mano follow konid mamnoon mishamm","lotfan az man hemayat konid ... mercc."])
	time.sleep(179)
	session.like_by_tags(["noshahr"], amount=1,randomize=True)
	session.set_do_comment(True,percentage=100)
	session.set_comments(["age mishe mano follow konid","lotfan mano follow konid!!","mamnoon misham mano follow konid!!","mishe mano follow konid?!!","lotfan mano follow konid dooste aziz!!","salam age momkene mano follow konid!!","kheili khube , lotfan page e man ro ham bebinid!", "age emkanesh hast mano follow konid lotfan!!", "mishe axaye mano like koni?!!", "lotfan mano follow konid!!", "mishe khahesh konam mano follow konid?!!","lotf konid man ro ham follow konid!!","lotfan age emkansh hast mano follow konid!!","mishe khahesh konam az man hemayat konid?!!","age lotf konid mano follow konid mamnoon misham!!","lotfan az man hemayat konid ... merc!!."])
	time.sleep(172)
	session.like_by_tags(["chalus"], amount=1,randomize=True)
	session.set_do_comment(True,percentage=100)
	session.set_comments(["Age mishe mano follow konid","lotfan mano follow konid","Mamnoon misham mano follow konid","mishe mano follow konid?","Lotfan mano follow konid dooste aziz","Salam age momkene mano follow konid","Kheili khube , lotfan page e man ro ham bebinid", "Age emkanesh hast mano follow konid lotfan", "Mishe axaye mano like koni?", "Lotfan mano follow konid", "Mishe khahesh konam mano follow konid?","Lotf konid man ro ham follow konid","Lotfan age emkansh hast mano follow konid","Mishe khahesh konam az man hemayat konid?","Age lotf konid mano follow konid mamnoon misham","Lotfan az man hemayat konid ... Merc."])
	time.sleep(195)
	session.like_by_tags(["ramsar"], amount=1,randomize=True)
	session.set_do_comment(True,percentage=99)
	session.set_comments(["age mishe mano follow konid","lotfan mano follow konid","mamnoon misham mano follow konid","mishe mano follow konid?","lotfan mano follow konid dooste aziz","salam age momkene mano follow konid","kheili khube , lotfan page e man ro ham bebinid", "age emkanesh hast mano follow konid lotfan", "mishe axaye mano like koni?", "lotfan mano follow konid", "mishe khahesh konam mano follow konid?","lotf konid man ro ham follow konid","lotfan age emkansh hast mano follow konid","mishe khahesh konam az man hemayat konid?","age lotf konid mano follow konid mamnoon misham","lotfan az man hemayat konid ....... merc."])
	time.sleep(177)
	session.like_by_tags(["gorgan"], amount=1,randomize=True)
	session.set_do_comment(True,percentage=100)
	session.set_comments(["age mishe mano follow konid","lotfan mano follow konid","mamnoon misham mano follow konid","mishe mano follow konid?","lotfan mano follow konid dooste aziz","salam age momkene mano follow konid","kheili khube , lotfan page e man ro ham bebinid", "age emkanesh hast mano follow konid lotfan", "mishe axaye mano like koni?", "lotfan mano follow konid", "mishe khahesh konam mano follow konid?","lotf konid man ro ham follow konid","lotfan age emkansh hast mano follow konid","mishe khahesh konam az man hemayat konid?","age lotf konid mano follow konid mamnoon misham","lotfan az man hemayat konid ...... merc."])
	time.sleep(186)
	session.like_by_tags(["golestan"], amount=1,randomize=True)
	session.set_do_comment(True,percentage=90)
	session.set_comments(["age mishe mano follow konid","lotfan mano follow konid","mamnoon misham mano follow konid","mishe mano follow konid?","lotfan mano follow konid dooste aziz","salam age momkene mano follow konid","kheili khube , lotfan page e man ro ham bebinid", "age emkanesh hast mano follow konid lotfan", "mishe axaye mano like koni?", "lotfan mano follow konid", "mishe khahesh konam mano follow konid?","lotf konid man ro ham follow konid","lotfan age emkansh hast mano follow konid","mishe khahesh konam az man hemayat konid?","age lotf konid mano follow konid mamnoon misham","lotfan az man hemayat konid ............ merc."])
	time.sleep(173)
	session.like_by_tags(["babol"], amount=1,randomize=True)
	session.set_do_comment(True,percentage=90)
	session.set_comments(["age mishe mano follow konid","lotfan mano follow koniiiiiiid","mamnoon misham mano folllow konid","mishe mano follow koniiiiiid?","lotfan mano follow konid dooste aziiiiiiz","salam age momkene mano follow koniiiiiiid","kheili khube , lotfan page e man ro ham bebiniiiiiid", "age emkanesh hast mano follow konid lotfaaa", "mishe axaye mano like koni?", "lotfan mano follow konid", "mishe khahesh konam mano follow konid?","lotf konid man ro ham follow konid","lotfan age emkansh hast mano follow konid","mishe khahesh konam az man hemayat konid?","age lotf konid mano follow konid mamnoon misham","lotfan az man hemayat konid ... merc."])
	time.sleep(187)
	session.like_by_tags(["sanandaj"], amount=1,randomize=True)
	session.set_do_comment(True,percentage=90)
	session.set_comments(["age mishe mano follow konid","lotfan mano follow konid","mamnoon misham mano follow konid","mishe mano follow konid?","lotfan mano follow konid dooste aziz","salam age momkene mano follow konid","kheili khube , lotfan page e man ro ham bebinid", "age emkanesh hast mano follow konid lotfan", "mishe axaye mano like koni?", "lotfan mano follow konid", "mishe khahesh konam mano follow konid?","lotf konid man ro ham follow konid","lotfan age emkansh hast mano follow konid","mishe khahesh konam az man hemayat konid?","age lotf konid mano follow konid mamnoon misham","lotfan az man hemayat konid ... merc."])
	time.sleep(189)
	session.like_by_tags(["kordestan"], amount=1,randomize=True)
	session.set_do_comment(True,percentage=80)
	session.set_comments(["age mishe mano follow konid","lotfan mano follow konid","mamnoon misham mano follow konid","mishe mano follow konid?","lotfan mano follow konid dooste aziz","salam age momkene mano follow konid","kheili khube , lotfan page e man ro ham bebinid", "age emkanesh hast mano follow konid lotfan", "mishe axaye mano like koni?", "lotfan mano follow konid", "mishe khahesh konam mano follow konid?","lotf konid man ro ham follow konid","lotfan age emkansh hast mano follow konid","mishe khahesh konam az man hemayat konid?","age lotf konid mano follow konid mamnoon misham","lotfan az man hemayat konid ... merc."])
	time.sleep(186)
	session.like_by_tags(["andarzgoo"], amount=1,randomize=True)
	session.set_do_comment(True,percentage=80)
	session.set_comments(["age mishe mano follow konid","lotfan mano follow konid","mamnoon misham mano follow konid","mishe mano follow konid?","lotfan mano follow konid dooste aziz","salam age momkene mano follow konid","kheili khube , lotfan page e man ro ham bebinid", "age emkanesh hast mano follow konid lotfan", "mishe axaye mano like koni?", "lotfan mano follow konid", "mishe khahesh konam mano follow konid?","lotf konid man ro ham follow konid","lotfan age emkansh hast mano follow konid","mishe khahesh konam az man hemayat konid?","age lotf konid mano follow konid mamnoon misham","lotfan az man hemayat konid ... merc."])
	time.sleep(199)
session.end()
